qede_hash_get_txq should be under #ifdef NO_CROSSBOW
The qede_hash_get_txq is only used if no crossbow is defined. We should
build it under that. Causes the following warning:

cc1: warnings being treated as errors
../../common/io/qede/qede_fp.c:1644: error: 'qede_hash_get_txq' defined
but not used [-Wunused-function]
*** Error code 1