Remove trailing comment. This caused gcc to error with the following:
In file included from
../../common/io/qede/579xx/drivers/ecore/ecore_hw.c:36:
../../common/io/qede/579xx/drivers/ecore/bcm_osal.h:423:3: error:
multi-line comment